### PR TITLE
Add HTML, and fix list_block and image inline errors

### PR DESCRIPTION
**Pull request by ericholscher**
Fixed a couple small bugs, and added inline HTML support. Not 100% sure about my `list_block` or `html_block` changes, but I'm starting to understand the code better.

### CODE REVIEW

**Comment by ericholscher** [comment]
Any thoughts on this? This adds an optional dependency on Sphinx for processing the extensions -- which should probably be a dependency on core docutils for now. Other than that though, it should be workable.

**Comment by ericholscher** [comment]
I went ahead and commented on the Markdown forum, asking about an official extension syntax. I'm guessing that it's at least 3 months off, so I'm going to plan on not supporting it for now. Once it gets into the spec, it should be relatively easy to add support for it though.

http://talk.commonmark.org/t/generic-directives-plugins-syntax/444/129?u=ericholscher

**Comment by lu-zero** [comment]
Agreed! Thanks a lot!

**Comment by lu-zero** [comment]
Somehow I forgot to merge this... Got new changes spending? I had been horribly busy ^^;

**Pull request merged**
